# Generated by Django 2.1.3 on 2019-03-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Shipping to? Who is it for?', max_length=120, null=True)),
                ('nickname', models.CharField(blank=True, help_text='Internal Reference Nickname', max_length=120, null=True)),
                ('address_type', models.CharField(choices=[('billing', 'Billing address'), ('shipping', 'Shipping address')], max_length=120)),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(default='United States of America', max_length=120)),
                ('state', models.CharField(choices=[('AL-Alabama', 'Alabama'), ('AZ-Arizona', 'Arizona'), ('AR-Arkansas', 'Arkansas'), ('CA-California', 'California'), ('CO-Colorado', 'Colorado'), ('CT-Connecticut', 'Connecticut'), ('DE-Delaware', 'Delaware'), ('DC-District of Columbia', 'District of Columbia'), ('FL-Florida', 'Florida'), ('GA-Georgia', 'Georgia'), ('ID-Idaho', 'Georgia'), ('IL-Illinois', 'Illinois'), ('IN-Indiana', 'Indiana'), ('IA-Iowa', 'Iowa'), ('KS-Kansas', 'Kansas'), ('KY-Kentucky', 'Kentucky'), ('LA-Louisiana', 'Louisiana'), ('ME-Maine', 'Maine'), ('MD-Maryland', 'Maryland'), ('MA-Massachusetts', 'Massachusetts'), ('MN-Minnesota', 'Minnesota'), ('MI-Michigan', 'Michigan'), ('MS-Mississippi', 'Mississippi'), ('MO-Missouri', 'Missouri'), ('MT-Montana', 'Montana'), ('NE-Nebraska', 'Nebraska'), ('NV-Nevada', 'Nevada'), ('NH-New Hampshire', 'New Hampshire'), ('NJ-New Jersey', 'New Jersey'), ('NM-New Mexico', 'New Mexico'), ('NY-New York', 'New York'), ('NC-North Carolina', 'North Carolina'), ('ND-North Dakota', 'North Dakota'), ('OH-Ohio', 'Ohio'), ('OK-Oklahoma', 'Oklahoma'), ('OR-Oregon', 'Oregon'), ('PA-Pennsylvania', 'Pennsylvania'), ('RI-Rhode Island', 'Rhode Island'), ('SC-South Carolina', 'South Carolina'), ('SD-South Dakota', 'South Dakota'), ('TN-Tennessee', 'Tennessee'), ('TX-Texas', 'Texas'), ('UT-Utah', 'Utah'), ('VT-Vermont', 'Vermont'), ('VA-Virginia', 'Virginia'), ('WA-Washington', 'Washington'), ('WV-West Virginia', 'West Virgini'), ('WI-Wisconsin', 'Wisconsin'), ('WY-Wyoming', 'Wyoming')], max_length=120)),
                ('postal_code', models.CharField(max_length=120)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
            ],
        ),
    ]
