# Generated by Django 2.1.3 on 2019-03-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name=''),
        ),
    ]
