# Generated by Django 2.1.3 on 2019-03-28 21:31

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190312_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/Samir/Documents/ayoub/magic/pyAyoub/jhoninventory/static_cdn/protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
