# Generated by Django 2.2 on 2019-04-22 13:59

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190328_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/ayoub/Documents/pyAyoub/pyAyoub/jhoninventory/static_cdn/protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
